name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky26b
        with:
          pdk: sky130A

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky26b
